
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlbfvnbltbupfnufkrjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYmZ2bmJsdGJ1cGZudWZrcmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTIzNzUsImV4cCI6MjA2MjM2ODM3NX0.KVGTlndCtQYKK08YcdhTq_JXO446BLIOX_AfhW80pqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
